# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20170909_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='Purpose of the organization'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
