# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20170909_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfileProposedChange',
            fields=[
                ('organizationprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.OrganizationProfile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='organization.OrganizationProfile')),
            ],
            options={
                'verbose_name': 'Organization profile proposed change',
                'verbose_name_plural': 'Organization profile proposed changes',
            },
            bases=('organization.organizationprofile',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='ID in KRS database')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='full_name')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='position')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='external_department_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='organization.Category'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='krs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='administration',
            field=models.ManyToManyField(related_name='administers', to='organization.Person', verbose_name='organization|administration'),
        ),
        migrations.AddField(
            model_name='organization',
            name='supervisory_authority',
            field=models.ManyToManyField(related_name='supervise', to='organization.Person', verbose_name='organization|supervisory authority'),
        ),
    ]
