# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(verbose_name='ID in KRS database')),
                ('nip', models.IntegerField()),
                ('krs', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_name', models.CharField(max_length=255, verbose_name='Short name')),
                ('purpose', models.TextField(verbose_name='Purpose of the organization')),
                ('register_at', models.DateField(verbose_name='Date of the registration')),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=255)),
                ('flat_number', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
